# Generated by Django 4.1.2 on 2023-09-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0004_alter_inventory_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_sold',
            field=models.BigIntegerField(default=0),
        ),
    ]
